# Site settings
title: Work in progress.
#email: https://nicolabs.net/contact
description: > # this means to ignore newlines until "baseurl:"
  This article is under perpetual rewriting, take it carefully as it may have changed tomorrow !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicolabs.net" # the base hostname & protocol for your site
twitter_username: nic0b0
github_username:  nicolabs

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
