# SEO settings
title: nicolabs
description: Work in progress.
keywords: "android, development, java, javascript, python, web"
url: https://www.nicolabs.net
#baseurl: ""
baseurl: null

repo:
  url: https://github.com/nicolabs/nicolabs.github.io
  # Path to add to `repo.url` to get the commits history root URL
  commits_path: commits/master
disqus_shortname: nicolabs
# Required for GitHub Pages
destination: docs

# Build settings
permalink   : /:year/:title
markdown    : kramdown
highlighter : rouge

collections:
  preposts:
    output: true
    permalink: /:year/:title

# TODO From where does this parameter comes from ?
comments: false

pagination:
    enabled: true
    permalink: '/page/:num/'    # Pages are html files, linked jekyll extensionless permalink style.
#    #locale: en

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # expanded

# Author settings
author:
  name     : nicobo
  job      : Software Engineer
  bio      : "I'm interested into whatever is called technology and this is my <strong class=\"author-name\" itemprop=\"name\">lab's</strong> log."
  thumb    : /assets/about/nicobo.png
  url      : https://nicolabs.net/contact
  github   : https://github.com/nicolabs
  twitter  : nic0b0
  mastodon:
    instance: https://mastodon.social
    username: "@nicobo"

# social settings
og_locale: en_US
og_locale_alternate: [fr_FR]

# It looks like the following list is totally controlled on github pages : https://help.github.com/articles/configuring-jekyll-plugins/
# More accurate : https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
plugins:
    # Default plugins from github
    - jekyll-coffeescript
    - jekyll-commonmark-ghpages
    - jekyll-gist
    - jekyll-github-metadata
    - jekyll-paginate
    - jekyll-relative-links
    - jekyll-optional-front-matter
    - jekyll-readme-index
    - jekyll-default-layout
    - jekyll-titles-from-headings
    # More plugins for this site
    # - nicolabs-feed-collection
    - jekyll-feed
    #- jekyll-paginate-v2
    - jekyll-redirect-from
    - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
