# SEO settings
title: nicolabs
description: Work in progress.
keywords: "android, development, java, javascript, python, web"
url: https://nicolabs.net
#baseurl: ""
baseurl: null

repo: https://github.com/nicolabs/nicolabs.github.io
disqus_shortname: nicolabs

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 4
paginate_path: "/page/:num/"
comments: false

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # expanded

# Author settings
author:
  name     : nicobo
  job      : Software Engineer
  bio      : "I'm interested into whatever is called technology and this is my lab's log."
  thumb    : /images/author.png
  url      : https://nicolabs.net/contact
  github   : https://github.com/nicolabs
  twitter  : nic0b0
  mastodon : https://mastodon.social/@nicobo

# social settings
og_locale: en_US
og_locale_alternate: [fr_FR]

# It looks like the following list is totally controlled on github pages : https://help.github.com/articles/configuring-jekyll-plugins/
# More accurate : https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
plugins:
  - jekyll-feed
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
