# Site settings
title: nicolabs
#email: https://nicolabs.net/contact
description: > # this means to ignore newlines until "baseurl:"
  From personal notes to technical articles, in the hope it will be useful to somebody one day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicolabs.net" # the base hostname & protocol for your site
twitter_username: nic0b0
github_username:  nicolabs

# Build settings
markdown: kramdown
